### ISSUE TITLE
Invalid Email Upon Update

### ISSUE THREAD

**Issue by alex-mac** [davidroffe/imgpool#2]
When updating my email in the accounts page, I'm not informed that the email I want to update with is invalid.

## Steps to Reproduce

1. Navigate to the [Accounts Page](https://imgpool.app/account)
2. Click on "edit" next to the Account Email
3. Try to update the email to "1.2.3"
4. Click Submit

**Comment by davidroffe** [comment]
Bug squashed. 👍
