### ISSUE TITLE
Account Bio Not Persistent

### ISSUE THREAD

**Issue by alex-mac** [davidroffe/imgpool#3]
Upon updating the Bio in the [Account Page](https://imgpool.app/account), the user is presented with an empty input field. This may be troubling if there was a small typo in the bio that a user wanted to quickly fix.

## Steps to Reproduce
1. Go to the [Account Page](https://imgpool.app/account)
2. Click on "edit" next to the Account Bio
3. Type in something (anything really)
4. Click on Submit
5. Click on "edit" next to the Account Bio (again)
6. Notice that the previous bio does not populate the input area

**Comment by davidroffe** [comment]
When editing bio, the textarea is now populated with current bio.
